mvn archetype:generate \
    -DarchetypeArtifactId=service-extension-archetype \
    -DarchetypeGroupId=com.backbase.archetype \
    -DarchetypeVersion=11.1.0 \
    -DserviceGroupId=com.backbase.dbs.paymentorder \
    -DserviceArtifactId=payment-order-service \
    -DdbsVersion=2.19.1 \
    -DgroupId=com.backbase.dbs.paymentorder \
    -DartifactId=lorem-ipsum-batch-type-service-extension \
    -Dversion=1.0.0-SNAPSHOT \
    -Dpackage=com.backbase.dbs.payment.route \
    --batch-mode