server:
  port: 9915

# API Registry client configuration
eureka:
  instance:
    metadata-map:
      public: true
      role: live
  client:
    serviceUrl:
      defaultZone: http://localhost:8764/registry/eureka/

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

# Spring health monitoring
management:
  health:
    jms:
     enabled: false

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/greetings
#    username: greetings
#    password: Gr33:t1ngs
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database: mysql
#    generate-ddl: false
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:greetingsdb;Mode=Oracle
    platform: h2
    continue-on-error: true
  jpa:
    generate-ddl: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.yaml

buildingblocks:
  security:
    xss:
      autoconfig: false